"""init migr

Revision ID: 130e771e7238
Revises: 35ffb602f4b8
Create Date: 2023-09-25 13:06:14.157719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '130e771e7238'
down_revision = '35ffb602f4b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
