"""change name of image_path to file

Revision ID: a35db564ba27
Revises: e90c2e6d5d03
Create Date: 2023-08-10 21:25:18.906449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35db564ba27'
down_revision = 'e90c2e6d5d03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
