"""remarked SkuImage table

Revision ID: b6bd5d6304d1
Revises: 6191a6aa322d
Create Date: 2023-07-26 17:45:17.500051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b6bd5d6304d1"
down_revision = "6191a6aa322d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sku_image",
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("sku_id", sa.UUID(), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.uuid"], name=op.f("fk__sku_image__sku_id__sku")
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk__sku_image")),
    )
    op.create_index(op.f("ix__sku_image__uuid"), "sku_image", ["uuid"], unique=True)
    op.drop_index("ix__Sku_image__uuid", table_name="Sku_image")
    op.drop_table("Sku_image")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Sku_image",
        sa.Column("path", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "deleted_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "uuid",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sku_id"], ["sku.uuid"], name="fk__Sku_image__sku_id__sku"
        ),
        sa.PrimaryKeyConstraint("uuid", name="pk__Sku_image"),
    )
    op.create_index("ix__Sku_image__uuid", "Sku_image", ["uuid"], unique=False)
    op.drop_index(op.f("ix__sku_image__uuid"), table_name="sku_image")
    op.drop_table("sku_image")
    # ### end Alembic commands ###
