"""rename Product table to Sku

Revision ID: e2f19c5f2fed
Revises: cae2a1f29ee8
Create Date: 2023-07-25 16:35:29.492185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e2f19c5f2fed"
down_revision = "cae2a1f29ee8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
