"""remove nullable value for image column

Revision ID: e90c2e6d5d03
Revises: fe5be70a26eb
Create Date: 2023-08-10 15:15:34.174249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90c2e6d5d03'
down_revision = 'fe5be70a26eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brand', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('category', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('collection', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('color', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('collection', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('category', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('brand', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
