"""rename image column to image_path

Revision ID: fe5be70a26eb
Revises: b6bd5d6304d1
Create Date: 2023-07-26 23:24:50.842757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe5be70a26eb"
down_revision = "b6bd5d6304d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
