name: Check
on:
  push:
    paths-ignore: ["*.txt", "*.ini"]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgresql:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: infanta_test
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Create .env file
        run: |
          touch .env
          echo SECURITY_KEY=${{secrets.SECURITY_KEY}} >> .env
          echo POSTGRESQL_DSN=${{secrets.POSTGRESQL_DSN}} >> .env

      - name: Install dependecies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest
