name: Check
on:
  push:
    paths-ignore: ["*.txt", "*.ini"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependecies
        run: pip install -r requirements.txt

      - name: Lint code
        run: black
